### PR TITLE
Embeded RAMP3 and RAMP4 into home and demo pages

### PR DESCRIPTION
**Pull request by dnlnashed**
### Related Item(s) ###
#40 

### Changes ###
- Each feature on the Home page now displays an instance of RAMP3 and RAMP4 instead of an image of RAMP3
    - To switch between either version, two buttons were added on top of the map
- Similar case for the individual demo pages as well, can switch to RAMP4 now

### Notes ###
- Config is now split into two files, one for RAMP3 configs and another for RAMP4 configs
- The version of RAMP4 being used is v4.1.0. 
- The demos for the feature collection area of the website (easy-to-implement, clip n ship, plugins) do not have a RAMP4 instance and are still the same. 
    - The reason for this was primarily due to the plugins section, as based on the notes for[ RAMPs v4.0.0 release](https://github.com/ramp4-pcar4/ramp4-pcar4/releases/tag/v4.0.0) it doesn't seem like RAMP4 supports the same level of plugin ability as RAMP3 does. Unsure if this is still the case, open to ideas on what should be done for RAMP4 in this section.
    - Can still add RAMP4 to the other two sections (easy-to-implement, clip n ship) if desired
    
### Issues/Future Work ###
- Because the home page is rendering 10 instances of RAMP (5 for RAMP4 and 5 for RAMP3) on start up, interacting with the website for the first couple of seconds is rough. Once everything is done loading, the website works well
    - One idea I've been looking into is to load each instance as the user first sees it instead of everything on start up
- Weird bug I found when playing with the RAMP4 instances, whenever you click the icon next to the layer name in the legend, the screen flicks to a specific position. Not sure if this is RAMP4 related or website related
- When setting up configs for RAMP4, I was able to make it so the grid would initially appear, but was not able to load the grid with data. Not sure if there is a way to do this, most likely just a me error
- If desired, add scrollguard to RAMP4 instances on the home page
- Make sure everything looks good on different browsers and screens, specifically mobile view
- Don't look at the console (working on clearing it up)

### Points ###
- Any feedback on this one is appreciated, especially the changes to the design and whether or not its best to have R3 and R4 instances for both the home and demo pages.
    - Biggest drawback right now is the performance of the home page.
    - Could have images for R3 and R4 on the home page and use the buttons to switch between them
- Will contine working on the issues above, I think the most important one right now is to make the initial load up of the website smoother.
- Feel free to wait until the demo build is set up. Here is a recorded demo (sadly limit is 10 mb)
help-menu-searching

Demo: https://ramp4-pcar4.github.io/ramp-website/ramp_switch/

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54)

### CODE REVIEW

**Review by szczz — CHANGES_REQUESTED** [review]
> Can still add RAMP4 to the other two sections (easy-to-implement, clip n ship) if desired

Will wait for more sage RAMP wisdom, but if its not possible to add it to the plugins section I think we should still proceed with implementing easy-to-implement and clip n ship.

> Because the home page is rendering 10 instances of RAMP (5 for RAMP4 and 5 for RAMP3) on start up, interacting with the website for the first couple of seconds is rough. Once everything is done loading, the website works well
> 
> -   One idea I've been looking into is to load each instance as the user first sees it instead of everything on start up

The load wasn't terrible on my machine, but I think this is a good idea anyways especially for mobile devices. Once the demo builds are set up we can test the experience on the ol' cellular device.

> Weird bug I found when playing with the RAMP4 instances, whenever you click the icon next to the layer name in the legend, the screen flicks to a specific position. Not sure if this is RAMP4 related or website related

Hmm, perhaps we need a `event.preventDefault();` somewhere. I'll look a bit closer this afternoon.

> Make sure everything looks good on different browsers and screens, specifically mobile view

Woops you're already on it! Ignore the point made in my code review. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-:-N_nYSm-0blzIIh8YESE:b-y94qg2)* status: all files reviewed, 2 unresolved discussions (waiting on @dnlnashed)

**Review by dnlnashed — COMMENTED** [review]
Here is a link: https://ramp4-pcar4.github.io/ramp-website/ramp_switch/

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-:-NamOQdv5ceP_c_HVlbE:bqythq5)* status: 28 of 31 files reviewed, 2 unresolved discussions (waiting on @szczz)

**Comment by james-rae** [comment]
> due to the plugins section, as based on the notes for RAMPs v4.0.0 release it doesn't seem like RAMP4 supports the same level of plugin ability as RAMP3 does. Unsure if this is still the case, open to ideas on what should be done for RAMP4 in this section.

It's a bit different is all. Both RAMPs let you build your own custom nonsense and put it in the app. Both also have things that are optional but "just come with RAMP". What may be confusing is the architecture.

RAMP2 had lots of "set in stone" things, and the odd optional things were called plugins. RAMP4, fixtures are the plugins. So for something like "Areas Of Interest", it's a RAMP2 plugin, and a RAMP4 non-default fixture. But in RAMP4 the legend is also a "plugin". You can run RAMP4 without the legend. You couldn't do this in RAMP2.

> clip n ship

We don't have this in RAMP4. The data grid will filter but we have no export capabilities at the moment.

> When setting up configs for RAMP4, I was able to make it so the grid would initially appear, but was not able to load the grid with data. Not sure if there is a way to do this

No still a pending feature https://github.com/ramp4-pcar4/ramp4-pcar4/issues/909

**Comment by spencerwahl** [comment]
I also vote for showing RAMP4 samples as the default since we want to show that off as our main thing.

On initial site load the RAMP divs pop in and move things around, might want to set the containing div to the proper size so the space is already there for it.

**Comment by james-rae** [comment]
Given the samples occupy a smaller view on the screen, I'm finding the default RAMP4 extent causes the view to be very far out. Though maybe this was done so that the legend isn't covering western canada (a different problem altogether).

Some of our sample layers are very heavy (like CESI Conserved Areas is one of the biggest poly sets we have, even as a Map Image Layer, its a crusher for performance). Getting slow load warnings, and the additional memory pressure of all that data in the browser on a page that already has like 8 frameworks installed is noticeable. Maybe make a spin off issue to address later (samples can always be updated). Something light and good looking is ideal; we can even look into making sample services specifically for this site.

The `WCAG Accessible - Without the "Clunk"` heading tends to word-wrap with "Clunk" on it's own line. Looks a bit.....clunky :older_man:. Maybe put the commentary about how grand we are into the paragraph and just have `WCAG Accessible` as the title?

Should the "Mobile Friendly" demo be sized down to a dimension that forces mobile mode on?

Portfolio: Climate Action Map has a broken basemap and apparently it's not getting fixed until it gets upgraded to RAMP4 or shut down. Maybe remove from the rotation for now?

**Comment by james-rae** [comment]
Cool as the live swap preview is, Firefox tells me the page memory footprint is currently over 700MB. Possible I'm reading it wrong or whatnot but that might be a reality we need to deal with (e.g. using screenshots and links to dedicated demo pages as alternatives)

**Comment by szczz** [comment]
>Cool as the live swap preview is, Firefox tells me the page memory footprint is currently over 700MB. Possible I'm reading it wrong or whatnot but that might be a reality we need to deal with (e.g. using screenshots and links to dedicated demo pages as alternatives)

Hmm perhaps instead of switching between R3 and R4 on the home page we instead just show R4 demos. Leave the switching to standalone demo pages?

**Comment by spencerwahl** [comment]
> footprint is currently over 700MB

Another issue is I had originally written this in vue2 to match RAMP4 for the eventual swap, with RAMP4 on vue3 its loading both versions of vue.

**Comment by james-rae** [comment]
R4 on main is worth a shot. Also looks like reviewable won't respect my edit; Trimming the dataset sizes will help some as well.

**Comment by szczz** [comment]
> R4 on main is worth a shot. Also looks like reviewable won't respect my edit; Trimming the dataset sizes will help some as well. 

Personally a big fan of the switching, I'm a sucker for buttons

Lets try trimming the datasets first then, if that's insufficient we can remove the R3 demos.

**Review by dnlnashed — COMMENTED** [review]
I'm also working on making the R3 and R4 instances for each feature render only when the user first sees them.
Thinking about it here though eventually everything will be rendered and we'll end up with 10 instances running at a time still.

Maybe one way could be to only render the R3 and R4 instances for a feature once the user sees it, and when they don't see it on the screen anymore we just don't render the instance. This way only two instances of RAMP are ever running at a time when the user is looking at the feature section, and none are running when the user isn't looking at it.

The only downside is that we will have to constantly rerender the instances if the user goes back to see them, but it should be much faster.

Not sure how reasonable or logical my logic is (feel free to tell me I'm completely off), but I do think rendering everything all the time will be a problem, as the performance will most likely get worse when we embed storylines onto the home page lol.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-:-NamaB9CB_iGM1zLZ9Ya:b-lzdztb)* status: 28 of 31 files reviewed, 2 unresolved discussions (waiting on @szczz)

**Review by szczz — CHANGES_REQUESTED** [review]
This definitely feels a lot smoother, however it still seems to be using a tonne of memory. I'll look into possible ways in which we can improve on this, but we may need to just display RAMP4 demos on the main page. We'll still show switching on the dedicated demo pages. 

Just a minor thing I noticed in the mobile view, the padding in the demo descriptions needs to be updated 



> Reviewed 1 of 3 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-:-NbzL-G_ChaWzQ7YgxYF:b-u4h5jl)* status: all files reviewed, 1 unresolved discussion (waiting on @dnlnashed)

___
*[`src/components/map.vue` line 76 at r3](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-NbyxaGq5c4S2ooGg_6Z:-NbyxaGq5c4S2ooGg_6_:b35dx89) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/122574abd782130230c65af5c1cf3730d6536f83/src/components/map.vue#L76)):*
> ```Vue
>     mounted() {
>         this.shadowValue = this.shadow === undefined ? false : this.shadow;
> ```

Think this could be this.shadow ?? false;

**Review by dnlnashed — COMMENTED** [review]
> This definitely feels a lot smoother, however it still seems to be using a tonne of memory. I'll look into possible ways in which we can improve on this, but we may need to just display RAMP4 demos on the main page. We'll still show switching on the dedicated demo pages.

I did try trimming the datasets earlier, but from what I saw memory usage was higher than normal still. Could maybe invest the time in making our own file layers, but the number of frameworks may be an issue. If we decide to keep only R4 on main, should be easy to implement.

> Just a minor thing I noticed in the mobile view, the padding in the demo descriptions needs to be updated

Padding added, doneThanks

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-:-Nbza4qp82DRWgzrPpsU:b-6orw8)* status: 31 of 33 files reviewed, 1 unresolved discussion (waiting on @szczz)

___
*[`src/components/map.vue` line 76 at r3](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-NbyxaGq5c4S2ooGg_6Z:-NbzZSCz4CN-ZpKoQwEL:bvr9fht) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/122574abd782130230c65af5c1cf3730d6536f83/src/components/map.vue#L76)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

Think this could be this.shadow ?? false;
</blockquote></details>

Good point, doneThanks

**Review by james-rae — COMMENTED** [review]
> If it is a R4 problem, could affect storylines for the eventual transition to R4 maps.

Yep. Will log an issue in R4 for this to be researched.

For trimming data and alt stuff, the two easiest things.

[Permanant filters](https://ramp4-pcar4.github.io/ramp4-pcar4/main/docs/using-ramp4/layer-config.html#permanentfilteredquery) which will cause a subset of stuff to be consumed and drawn. Downside is you need to look at the dataset, figure out the appropriate SQL, etc.

Inline small file layers via the [rawData](https://ramp4-pcar4.github.io/ramp4-pcar4/main/docs/using-ramp4/layer-config.html#rawdata) config property. Can generate stuff [here](http://geojson.io/#map=3.18/50.89/-91.58) then flatten to a string with minimal whitespace. The main downside is attributes need to be manually added, and you are limited to the basic renderers, or have to spend time defining a [custom renderer](https://ramp4-pcar4.github.io/ramp4-pcar4/main/docs/using-ramp4/layer-config.html#customrenderer)

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-:-Nbzc0YPCG2yQxsu1WS6:b2ay4xr)* status: 31 of 33 files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by dnlnashed — COMMENTED** [review]
Rebased, once demo link updates it should be up to date with everything and display storylines on the home page thanks to Yi Lei's PR

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54#-:-NcOQmA56RMOFSuh1MXp:b-9hw60)* status: 21 of 33 files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by yileifeng — APPROVED** [review]
> Reviewed 14 of 31 files at r1, 7 of 16 files at r3, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Pull request merged**
