### PR TITLE
Update storylines content

### LINKED ISSUE #71: Marketing Site: Storylines feedback
The Storylines demo – I like the form of it, but the content can be confusing… the right-side image of the first slide is a screenshot of another Storylines product which feels a bit recursive. Maybe just some generic graphic of a presentation or something? https://unsplash.com/s/photos/presentation?license=free

a.	The image slideshow could maybe feature images that aren’t pie charts – since one could/should use Storylines to create interactive pie charts instead of hosting static images. 
b.	~~The “Dynamic Slide” is a nice demonstration of the capabilities but I feel like the text of it could be cleaned up to explain just what’s actually going on (e.g. “Dynamic Slide” -> “Control your message with dynamic and interactive slides” or something like that. I can gussy this up later, but it will need to wait awhile.~~ We'll update this when we have metrics. That way we can send everything off for translation at once.
c.	I don’t know if it’s worth drawing a border around the whole area of the Storylines demo, just to “contain” it more as an embedded product/option?

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #71 

**Changes**
- adds a border around the embedded Storylines
- updated image content with birds and a presentation of Storylines
- properly added alt text descriptions with translations
- re-added the router lang query param on initial page load (accidently got removed last PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/73)

### CODE REVIEW

**Review by szczz — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/73)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`public/storylines/storylines_en.json` line 23 at r1](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/73#-Nd5kkk388kAWsbDLT01:-Nd5kkk388kAWsbDLT02:bwu3rfr) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/10c3588c9fc579b80876f970a43efbebba87de65/public/storylines/storylines_en.json#L23)):*
> ```JSON
>                     "src": "storylines/assets/RAMP2.png",
>                     "type": "image",
>                     "altText": "A map displaying hundreds of Pulp & Paper facilities across Canada.",
> ```

This should be updated to "A person presenting to their colleagues."

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/73)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @szczz)

___
*[`public/storylines/storylines_en.json` line 23 at r1](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/73#-Nd5kkk388kAWsbDLT01:-Nd5nKJ47OfFQ-fVefLg:bah2568) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/10c3588c9fc579b80876f970a43efbebba87de65/public/storylines/storylines_en.json#L23)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

This should be updated to "A person presenting to their colleagues."
</blockquote></details>

Donethanks

**Review by dnlnashed — APPROVED** [review]
> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/73)* status: all files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by szczz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
