### PR TITLE
Embed sample storylines product onto marketing page

### LINKED ISSUE #41: Embed storylines on the main page
Currently we just have an image of a storyline but it would be great if it was interactive. Ideally the existing storylines section would be replaced with a storylines instance. 

The team is working on enabling storylines to be imported as a standalone component. If this is successful we should attempt to embed an instance directly on the main page.

image

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #41 

### Changes ###
- adds Storylines plugin package and integrated in the StoryRamp feature section
- created a basic Storylines demo config showcasing all of the core panel functionality (mainly stored different panel types through a dynamic slide to conserve space) 
- changed Tailwind/i18n + other dependency updates to avoid styling and compatibility issues 

### Notes ### 
- if there are is any feedback for content changes in the demo Storylines product, feel free to leave suggestions
- a lot of newly introduced console errors that still need to be fixed 
- EDIT: panels cannot be opened for RAMP, due to offscreen error

### Demo ### 
Here is a quick preview of how the Storylines product looks on the page: 

storylines

[Demo](https://ramp4-pcar4.github.io/ramp-website/embed-storylines/#/?lang=en)

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55)

### CODE REVIEW

**Review by spencerwahl — APPROVED** [review]
Seems like page styles might still be interfering with the storylines styles, like the dynamic slide links. Looks to all function correctly though :+1:

> Reviewed 6 of 18 files at r1, 14 of 17 files at r2, 22 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55#-:-NawUiw5-T2HOgaKro_9:b-t9j7uv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
Fixed the dynamic slide links styling and the dynamic panel ToC bug from earlier + other mobile adjustments. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55#-:-NbL7jQ7CMvvvx4tKwlI:bsl1lzn)* status: 41 of 42 files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by szczz — APPROVED** [review]
> Reviewed 14 of 17 files at r2, 21 of 22 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
There seems to be an offscreen error check occurring when opening a panel for a map in the embedded Storyline. This might be related to targeting the wrong map div since when I remove the first map at the top of the page everything works fine. We recently pushed a similar fix in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/4130 so maybe we need to open a new issue to update to the latest RAMP3 build and check if this is resolved after.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55#-:-Nb_JNf9DJYC2-9x-V_R:b284q0l)* status: 40 of 42 files reviewed, all discussions resolved (waiting on @spencerwahl and @szczz)

**Review by james-rae — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 14 of 17 files at r2, 20 of 22 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
Offscreen panel errors all gone now with the RAMP3 build update. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55#-:-Nc8zdJE2cIPD7FypaWf:b-os8vns)* status: 40 of 42 files reviewed, all discussions resolved (waiting on @james-rae, @spencerwahl, and @szczz)

**Review by szczz — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 14 of 17 files at r2, 18 of 22 files at r3, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
