### PR TITLE
Fix map extent and mobile demos

### PR DESCRIPTION
**Pull request by dnlnashed**
For #70 

### Changes ###
- Map extents for the home page maps are now changed to have a better initial view of the map
- The mobile map on the home page is now sized to a proper mobile format
- The mobile demo page now does what it mentions in the description - 3 maps are displayed, each in different sizes.

Feel free to mention any feedback. May want to keep the mobile demo as it is now or maybe change it to something else.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74)

### CODE REVIEW

**Review by szczz — CHANGES_REQUESTED** [review]
Looks great! Can you just move the R3 & R4 buttons above the mobile demo please. The demo should also be centred in its existing container.

Something like this



> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74#-:-NdBp_lu0Io0YtQadSvO:b-si319u)* status: all files reviewed, 1 unresolved discussion (waiting on @dnlnashed)

___
*[`src/components/map.vue` line 17 at r1](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74#-NdBq2FtADbDF0AkA9jt:-NdBq2Fu8MmrBkycAiG8:b-ts8d6u) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/2ec90d2fb6e456c9452c35c92521745dd96b504f/src/components/map.vue#L17)):*
> ```Vue
>                 ultrices arcu pharetra at. Sed justo lacus, lacinia nec ex eget, semper ultrices enim. Nullam blandit
>                 convallis lectus, quis dictum lectus maximus eget. Maecenas ex dolor, dictum a faucibus vitae,
>                 sollicitudin sit amet augue. Aenean sollicitudin turpis in accumsan condimentum. Quisque lobortis odio a
> ```

Just curious what the placeholder text is for?

**Review by dnlnashed — COMMENTED** [review]
doneThanks I think. Wanted to make the position similar to the other features, but let me know if it looks off still. Also repositioned the rest of the toggle buttons to be on the edge above the map instead of slightly inwards.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74#-:-NdC1Kvh5t03iwfBjvhb:bccmqt)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @szczz)

___
*[`src/components/map.vue` line 17 at r1](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74#-NdBq2FtADbDF0AkA9jt:-NdCAd3m9iQEZ5bhc0P7:bchpa88) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/2ec90d2fb6e456c9452c35c92521745dd96b504f/src/components/map.vue#L17)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

Just curious what the placeholder text is for?
</blockquote></details>

I think its to try and show RAMP embedded within something since the description mentions showing a map embedded with text or page contents. Can remove the text and say in the desciption something along the lines of "full width, medium width, and mobile view".

**Review by szczz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74)* status: all files reviewed, 1 unresolved discussion (waiting on @dnlnashed)

___
*[`src/components/info/feature.vue` line 15 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74#-NdFzLhF5fc1uhmjZZhp:-NdFzLhF5fc1uhmjZZhq:b-6xgw2e) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/4ae4e6f175167221e9199144934a825bf6564aad/src/components/info/feature.vue#L15)):*
> ```Vue
>                 <div class="map-container md:mr-[20px]" v-if="index % 2 !== 0">
>                     <toggle-version @ramp3="openRAMP3" @ramp4="openRAMP4" :version="version" :key="version" />
>                     <div :class="{ 'flex justify-start': index === 5 }">
> ```

Button / demo alignment looks good, but it looks like the demo was moved under the buttons rather than the buttons shifted to the demo. This causes a large gap between the demo and the description text. Think it may have to do with this change.

**Review by dnlnashed — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @szczz)

___
*[`src/components/info/feature.vue` line 15 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74#-NdFzLhF5fc1uhmjZZhp:-NdG4XE96b_5AP11EdO8:b-u2g899) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/4ae4e6f175167221e9199144934a825bf6564aad/src/components/info/feature.vue#L15)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

Button / demo alignment looks good, but it looks like the demo was moved under the buttons rather than the buttons shifted to the demo. This causes a large gap between the demo and the description text. Think it may have to do with this change.
</blockquote></details>

Removed the gap and positioned everything to the center :+1:

**Review by yileifeng — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74)* status: all files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by dnlnashed — COMMENTED** [review]
Fixed position flickering when scrolling to the mobile demo on the home page when using a mobile device

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74#-:-NdGG9P04-WeY2N1nOgB:bfy2qf5)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @szczz and @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Pull request merged**
