### PR TITLE
Add PR demos

### PR DESCRIPTION
**Pull request by szczz**
#49 

Now that all of our major PRs have been opened, I figured it would be an excellent time to add demo links for PRs 🤡

Adapted from the R4MP action files

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/57)

### CODE REVIEW

**Review by yileifeng — COMMENTED** [review]
Missing the GH pages cleanup workflow for deleting demo folders on closed/merged PRs?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/57#-:-NaDAQC03txmilG5BRU0:b40oua9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Review by szczz — COMMENTED** [review]
donethanks. Added Miles as an admin to this repo in case its necessary. Updating the username and email just felt like it would be utter thievery.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/57#-:-NaDETsiDz0TIFvUn6ds:b-avcycs)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — APPROVED** [review]
🙈

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/57#-:-NaDGgoi2vj4u9RkQFqN:b44u40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Pull request merged**
