### PR TITLE
Initial implementation of the Contact Form 

### PR DESCRIPTION
**Pull request by szczz**
#39 

Initial implementation of the contact form. Emails are now sent to our RAMP inbox.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)

### CODE REVIEW

**Review by spencerwahl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @szczz)

___
*[`src/components/footer.vue` line 55 at r1](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZbLfnR1cMR2_BU6qOj:-NZbLfnR1cMR2_BU6qOk:bvz8egn) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/e7a33a8e900ee685739c125dcb1b7310067a7c5a/src/components/footer.vue#L55)):*
> ```Vue
>                             class="text-red-500 my-0"
>                         >
>                             Name is required.
> ```

Reminder to throw these in the lang file

**Review by szczz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[`src/components/footer.vue` line 55 at r1](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZbLfnR1cMR2_BU6qOj:-NZf_ORv4EMS0ZUhgPpR:b-mhsq5s) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/e7a33a8e900ee685739c125dcb1b7310067a7c5a/src/components/footer.vue#L55)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

Reminder to throw these in the lang file
</blockquote></details>

donethanks

**Review by yileifeng — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: all files reviewed, 5 unresolved discussions (waiting on @spencerwahl and @szczz)

___
*[`src/App.vue` line 37 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkf-1f5ToSsslsGdwx:-NZkf-1f5ToSsslsGdwy:b-czae1p) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/App.vue#L37)):*
> ```Vue
>         document.title = this.$i18n.t('page.title') as string;
>         document.documentElement.lang = this.$i18n.locale;
>         Vue.use(useToast);
> ```

Probably better to have this declaration in the `main.ts` entry file.
___
*[`src/components/footer.vue` line 216 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkmKmtA0Vgkx5p0k2f:-NZkmKmtA0Vgkx5p0k2g:bne9keg) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/components/footer.vue#L216)):*
> ```Vue
>     email = '';
>     details = '';
>     formError = false;
> ```

Noticed that we have a lot of `v-if="formError + condition"` residing in the template, wondering if this can be cleaned up a bit. My initial thoughts: 

1. Refactor `formError` into an object. This could look something like: 
```
formError = {
    reqName: false,
    reqEmail: false,
    reqDetails: false,
    invalidEmail: false,
    ...
}
```
with the purpose of replacing instances of `formError && !property` with `!formError[property]`. 

Then, in `sendEmail()` we can have: 
```
fields.forEach((field: string) => {
    if (!field) {
        error = true;
        // would need field name here and not the value
        this.formError[field] = true;
    }
 });

if (this.email && !this.isEmailValid(this.email)) {
    this.formError.invalidEmail = true;
}

```

It's a bit harder to test this without a demo build currently, but the approach makes some sense to me and should still be functional. Not sure if there will result in any object reactivity issues but that can be fixed too. 

2. We could add a parent container where it makes sense that checks `v-if="formError"`, which could shorten if statements to only be `!property`, downside is may need to add multiple divs.
___
*[`src/components/footer.vue` line 229 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkrzDIAU_IRhqTZI0U:-NZkrzDIAU_IRhqTZI0V:b5w32xh) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/components/footer.vue#L229)):*
> ```Vue
>         };
> 
>         const fields: string[] = [this.name, this.email, this.details];
> ```

Minor suggestion (based on variable name): we can just have field names here (`"name", "email", "details"`) and then call `data[field]` inside the for loop, good especially if we want to go with the object approach for `formError`. 
___
*[`src/components/header.vue` line 58 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkiqza3bUcU5Js-3Mn:-NZkiqza3bUcU5Js-3Mo:bnmdr6p) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/components/header.vue#L58)):*
> ```Vue
>                 </a>
>                 <a class="button font-bold border-4 border-black">
>                     <router-link to="/#footer">
> ```

Is this code linking to a footer element on the page or rendering the footer route? 

For the first case, having `<router-link :to="{ hash: '#footer'}"> ` should work, and then we can remove the footer route if not needed.

For the second, I think we can do `<router-link :to="{ name: 'Footer' }">` to utilize the route naming.

**Review by szczz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: 6 of 11 files reviewed, 5 unresolved discussions (waiting on @spencerwahl and @yileifeng)

___
*[`src/components/footer.vue` line 216 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkmKmtA0Vgkx5p0k2f:-NZlQ5IvBwmWbyvNg4ZQ:b-70xzdn) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/components/footer.vue#L216)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Noticed that we have a lot of `v-if="formError + condition"` residing in the template, wondering if this can be cleaned up a bit. My initial thoughts: 

1. Refactor `formError` into an object. This could look something like: 
```
formError = {
    reqName: false,
    reqEmail: false,
    reqDetails: false,
    invalidEmail: false,
    ...
}
```
with the purpose of replacing instances of `formError && !property` with `!formError[property]`. 

Then, in `sendEmail()` we can have: 
```
fields.forEach((field: string) => {
    if (!field) {
        error = true;
        // would need field name here and not the value
        this.formError[field] = true;
    }
 });

if (this.email && !this.isEmailValid(this.email)) {
    this.formError.invalidEmail = true;
}

```

It's a bit harder to test this without a demo build currently, but the approach makes some sense to me and should still be functional. Not sure if there will result in any object reactivity issues but that can be fixed too. 

2. We could add a parent container where it makes sense that checks `v-if="formError"`, which could shorten if statements to only be `!property`, downside is may need to add multiple divs.
</blockquote></details>

I like the idea, but currently the validation triggers on email save. After implementing the suggestion, if the user went back to modify the form the error would persist until they tried to submit again. I could move the validation out of the submit and into its own function, but then it would trigger on each input. The current approach only triggers the validation on submission and the errors go away once the user begins to fix it. If I were to take the object approach I would also need to define an interface for the formError and I would still require a separate variable for the email format error due to type differences between the fields. In some ways this cleans it up, but in other ways it might make it a bit messier.
___
*[`src/components/footer.vue` line 229 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkrzDIAU_IRhqTZI0U:-NZlS-zO2Z6FCYEWCEWK:b-4wd2wg) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/components/footer.vue#L229)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Minor suggestion (based on variable name): we can just have field names here (`"name", "email", "details"`) and then call `data[field]` inside the for loop, good especially if we want to go with the object approach for `formError`. 
</blockquote></details>

In addition to above, Typescript gets cranky if we do this because it expects the invalidEmail key to be present. I would need a separate variable for the email format error.
___
*[`src/components/header.vue` line 58 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkiqza3bUcU5Js-3Mn:-NZlSZvn2R3f1WL-k8q_:bqmzt6b) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/components/header.vue#L58)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Is this code linking to a footer element on the page or rendering the footer route? 

For the first case, having `<router-link :to="{ hash: '#footer'}"> ` should work, and then we can remove the footer route if not needed.

For the second, I think we can do `<router-link :to="{ name: 'Footer' }">` to utilize the route naming.
</blockquote></details>

Its linking to the footer element and simply scrolls to it. Updated to `<router-link :to="{ hash: '#footer'}">` and remove the route.

donethanks
___
*[`src/App.vue` line 37 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkf-1f5ToSsslsGdwx:-NZlPc8B0heZ9rX00JR-:b-mhsq5s) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/App.vue#L37)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Probably better to have this declaration in the `main.ts` entry file.
</blockquote></details>

donethanks

**Review by szczz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: 5 of 11 files reviewed, 3 unresolved discussions (waiting on @spencerwahl and @yileifeng)

___
*[`src/components/footer.vue` line 216 at r2](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44#-NZkmKmtA0Vgkx5p0k2f:-NZm59t420iUNL7o2_sH:b-m0wt8e) ([raw file](https://github.com/ramp4-pcar4/ramp-website/blob/0ccf382e3133a6bcb3732bdaa9f7d5fcdfc938da/src/components/footer.vue#L216)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

I like the idea, but currently the validation triggers on email save. After implementing the suggestion, if the user went back to modify the form the error would persist until they tried to submit again. I could move the validation out of the submit and into its own function, but then it would trigger on each input. The current approach only triggers the validation on submission and the errors go away once the user begins to fix it. If I were to take the object approach I would also need to define an interface for the formError and I would still require a separate variable for the email format error due to type differences between the fields. In some ways this cleans it up, but in other ways it might make it a bit messier.
</blockquote></details>

donethanks. Updated the footer with your suggested code.

**Review by yileifeng — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 5 of 7 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

**Review by spencerwahl — COMMENTED** [review]
> Reviewed 5 of 7 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: all files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by spencerwahl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/ramp-website/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Pull request merged**
